### ISSUE TITLE
bug: actions bar has not hide

### ISSUE THREAD

**Issue by yuxino** [diegoveloper/flutter_keyboard_actions#29] opened 2019-06-30 07:50 UTC
First i click the textField then i tap the prefixIcon to call `showModalBottomSheet`, the actions bar has not hide ..

See this video  _(•̀ω•́ 

https://www.youtube.com/watch?v=Phcsx1eB30Q&feature=youtu.be

**Comment by narayananulaganathan** [comment] 2019-07-01 09:59
+1 . Facing the same issue. Blocked on this. Expecting a solution for this. Also, only for iOS setting not working.

**Comment by yuxino** [comment] 2019-07-01 10:10
@narayananulaganathan In fact, I think we can manually add events listener to focusNode and then call `unfocus` . But I don't really want to manually do this.

**Comment by diegoveloper** [comment] 2019-07-01 14:34
Can anybody add a simple code to reproduce the issue?

**Comment by yuxino** [comment] 2019-07-01 15:05
@diegoveloper I will add a simple code to reproduce in tomorrow.

**Comment by yuxino** [comment] 2019-07-02 03:36
@diegoveloper https://github.com/yuxino/flutter_keyboard_actions_bug

**Comment by diegoveloper** [comment] 2019-07-02 03:46
I tried your example but I couldn't repo. Are you using Android or iOS?  I tested on iOS using flutter dev channel.

**Comment by yuxino** [comment] 2019-07-02 03:50
@diegoveloper I am using ios simulator (iphone xr), you can see action bar did't not hide. You can compare with `expected behavior`.

**Comment by diegoveloper** [comment] 2019-07-02 03:53
This is what I have : http://www.giphy.com/gifs/kdR4xajWFmlVf6LbWy

Flutter (Channel dev, v1.7.4)

**Comment by yuxino** [comment] 2019-07-02 03:59
@diegoveloper https://gph.is/g/Z7n6QPd

**Comment by diegoveloper** [comment] 2019-07-02 04:02
Run `flutter doctor` and paste

**Comment by yuxino** [comment] 2019-07-02 04:06
@diegoveloper 

``` shell
➜  flutter_keyboard_actions_bug git:(master) ✗ flutter doctor                   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)
```

- [bug](https://gph.is/g/ZWmL2n7)
- [ok](https://gph.is/g/aXpq3we)

**Comment by diegoveloper** [comment] 2019-07-02 04:07
Try changing the channel , run `flutter channel dev` ,   `flutter clean` , and try again.

**Comment by yuxino** [comment] 2019-07-02 06:02
@diegoveloper dev is ok ...

**Comment by diegoveloper** [comment] 2019-07-02 06:04
Ok, so it looks like a bug from stable version and eventually dev will merge to stable. I will close this issue.

**Closed by diegoveloper** 2019-07-02 06:04 UTC
