### ISSUE TITLE
Keyboard is hidden when I tap Android Home or Overview button but not keyboard actions header

### ISSUE THREAD

**Issue by ghunter99** [diegoveloper/flutter_keyboard_actions#1] opened 2018-12-15 08:55 UTC
Hi @diegoveloper, 

Thanks for writing this great package!

The only problem I've experienced is when the keyboard is displayed and:
1. I switch out of an app, using the Android Home button or the Overview button  (that's the third button at the bottom from the left)
2. I can see that the keyboard is hidden
3. When I return to the app the keyboard actions are sitting at the bottom of the screen without the keyboard being displayed.

The problem occurs in the example app and the apps that I've used the package in.

It seems like the package is not able to detect the keyboard being hidden in this situation.

I'm hoping it's simple for you to reproduce.

I've tried it on a few different versions of Android. My set up is fairly standard:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14 18A391, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.2)
[✓] Connected device (2 available)

Thanks

**Comment by diegoveloper** [comment] 2018-12-15 14:05
Hello, thanks for catch this issue. Are you able to reproduce on iOS ?

**Comment by diegoveloper** [comment] 2018-12-15 19:40
Hey, I could fixed the issue, it looks like only happens on Android.
To test the new changes please change this on your pubspec.yaml file :

```
keyboard_actions:
    git: https://github.com/diegoveloper/flutter_keyboard_actions.git
```
After you confirm it's working fine, I'll close the issue and upload a new version to the pub.

Thanks

**Comment by ghunter99** [comment] 2018-12-16 06:00
Wow, that was fast :smile:

Looks like it's almost working.

Yes, it only happens on Android. 
On iOS, keyboard is not hidden when press home or recent button.
Would be good if Flutter on Android behaved the same way.
I notice Chrome on Android does not hide keyboard when press home or recent button.
But nothing we can do about that.

I tested and keyboard actions are hidden correctly when press home or recent button.

On switch back to app however, old text field has focus but if I tap on old text field, keyboard is 
shown without keyboard actions (somehow focus node listener function is not called)

If I tap on a different text field everything works.

Hope you can replicate.

Maybe just call:
   FocusScope.of(context).requestFocus(_currentAction.focusNode);
when detect state change to pause?

Thanks again for this great package.

-Gary

**Comment by diegoveloper** [comment] 2018-12-16 06:17
Fixed now, could you try again?

**Comment by ghunter99** [comment] 2018-12-17 06:08
:thumbsup: Works great. Thanks!

**Closed** 2018-12-18 01:12 UTC
