### ISSUE TITLE
The action bar is not showing on Android

### ISSUE THREAD

**Issue by silviocandido** [diegoveloper/flutter_keyboard_actions#89] opened 2020-05-21 17:19 UTC
Hi, i need help, i'm use the example code but not work on Android, on iOS it's ok.

My setup:
Android 7.0
keyboard_actions: ^3.2.1+1
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.2 19C57, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

![image](https://user-images.githubusercontent.com/6479995/82586516-0f158d80-9b6e-11ea-8788-7e59e4bf11c7.png)

**Comment by diegoveloper** [comment] 2020-05-21 17:34
hmm it's working fine here using : v1.12.13+hotfix.9   , could you try with
another flutter version ?

>

**Comment by silviocandido** [comment] 2020-05-21 17:43
Thanks for listening.
I was using exactly this version. I updated in an attempt to resolve, but to no avail in both cases.
flutter doctor
     Flutter (Channel unknown, v1.12.13 + hotfix.9, on Mac OS X 10.15.2 19C57, locale en-US)

**Comment by diegoveloper** [comment] 2020-05-21 17:45
try using flutter clean, check if you have this variable
KeyboardActionsConfig(
keyboardActionsPlatform: KeyboardActionsPlatform.ALL,

**Comment by silviocandido** [comment] 2020-05-21 17:58
Unsuccessfully.
When I tap the textfield i can see fastly the action bar and than the keyboard is showed without the action bar.
I asked a friend to tes, look the screen:
![image](https://user-images.githubusercontent.com/6479995/82590087-75e97580-9b73-11ea-9f1a-8357ec7f6236.png)
I must be doing something very wrong, but I can't figure out what it is.

**Comment by diegoveloper** [comment] 2020-05-21 18:00
Can you reproduce the issue in the samples?

**Comment by silviocandido** [comment] 2020-05-21 18:09
No, I followed your suggest, flutter clean, and check "KeyboardActionsConfig(keyboardActionsPlatform.ALL" and flutter run
The first picture i sed is the sample code with the problem.

**Comment by diegoveloper** [comment] 2020-05-21 18:11
Show a video reproducing the issue using the sample from the package

**Comment by silviocandido** [comment] 2020-05-21 18:48
![20200521-153759-720x1280](https://user-images.githubusercontent.com/6479995/82594457-83562e00-9b7a-11ea-9c3f-751591144cc8.gif)

**Comment by silviocandido** [comment] 2020-05-21 18:52
Maybe is something wrong on my environment/project i tried use the old version keyboard_actions: ^2.1.2 with a code of other project that i know thats work and the problem was the same.
Any idea?

**Comment by diegoveloper** [comment] 2020-05-21 18:55
Does it happens for all the fields? Or only the first input field

**Comment by silviocandido** [comment] 2020-05-21 18:59
every one

**Comment by silviocandido** [comment] 2020-05-21 19:04
I created a empty project and put only the sample code and this time is work fine.
Maybe package incompatibility? Im using a lot:
  cupertino_icons: ^0.1.3
  provider: ^4.1.2
  shared_preferences: ^0.5.7+2
  page_transition: ^1.1.5
  fluttertoast: ^4.0.1
  cached_network_image: ^2.2.0+1
  objectdb: ^1.0.7+1
  epub_kitty: ^0.1.7
  path_provider: ^1.6.8
  dio: ^3.0.9
  permission_handler: ^5.0.0+hotfix.6
  google_sign_in: ^4.5.0
  flutter_facebook_login: ^3.0.0
  keyboard_actions: ^3.2.1+1
  flutter_html: ^1.0.0
  url_launcher: ^5.4.7
  firebase_core: ^0.4.0+9
  firebase_database: ^3.0.7
  firebase_messaging: 5.1.5
  flutter_multi_formatter: ^1.1.6
  intro_slider: ^2.3.1

**Comment by diegoveloper** [comment] 2020-05-21 19:07
yeah, it's probably related with the parent UI you use

**Comment by diegoveloper** [comment] 2020-05-21 19:07
I'll close the issue for now since there is no way to reproduce the issue from my side.

**Closed by diegoveloper** 2020-05-21 19:07 UTC

**Comment by silviocandido** [comment] 2020-05-22 08:45
Thanks for listening, and sorry for bothering you.
It was my fail. I created a new project, copied all the existing code and it worked perfectly.
The package is working correctly. Congratulations on the work.
